# Generated by Django 3.0.3 on 2020-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consumption_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption_record',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
