# Generated by Django 3.0.3 on 2020-02-12 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumption_record_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption_record',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
